### ISSUE TITLE
Add wsgi.py file for flask

### ISSUE THREAD

**Issue by RahulPalve** [RahulPalve/openforms#11]
currently we are running flask on prod server using local server, in order to use production grade server such as uvicorn. We need wsgi.py file which is configuration file and act as entrypoint.

**Comment by Preetraj2002** [comment]
sir i am a newbie in open source and deploying web apps. but this seems to be an amazing opportunity for me to learn. Please give me this task so that i can deepen my knowledge in this. Kindly consider assigning me this task

**Comment by RahulPalve** [comment]
Hi @Preetraj2002, Please take this up and let me know how much time will you need to complete this

**Comment by Preetraj2002** [comment]
give me today's time i will do it

**Comment by Preetraj2002** [comment]
i have facing difficulties in setting up the project
please guide me

pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 6520f35a0c0374b71b65f64f, topology_type: Single, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused')>]>


this is the issue on running setup_user.py
